# This file can be used to compile and run your program, instead of typing "gcc blah blah..." in the terminal everytime.

# USING THIS FILE - 

#1)

#2)

#3) In the terminal, make this file executable by typing (don't type the double quotes, of course) "chmod a+x MAKEFILE".

#4) Then type "./MAKEFILE LexFileName InputFileName" .

#---- END OF COMMENT ----

rm a.out
flex ../LexYacc_Specs/"$1".l
bison ../LexYacc_Specs/"$1".y
gcc "$1".tab.c -ly -ll
./a.out
